# Generated by Django 3.2.16 on 2022-12-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'объект', 'verbose_name_plural': 'объекты'},
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(max_length=60, verbose_name='тип'),
        ),
    ]
