# Generated by Django 3.2.16 on 2022-12-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_customquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Вопрос'),
        ),
    ]
