# Generated by Django 3.2.16 on 2022-12-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="intern",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="имя"
            ),
        ),
        migrations.AddField(
            model_name="intern",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="фамилия"
            ),
        ),
    ]
