# Generated by Django 3.2.16 on 2022-12-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_interviewed", models.EmailField(max_length=80)),
                ("questions", models.ManyToManyField(to="questions.Question")),
            ],
        ),
    ]
