# Generated by Django 3.2.16 on 2022-12-17 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("interviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionstatistic",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pack",
            name="questions",
            field=models.ManyToManyField(to="questions.Question"),
        ),
        migrations.AddField(
            model_name="interview",
            name="pack_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="interviews.pack",
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
