# Generated by Django 3.2.16 on 2022-12-14 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0002_auto_20221214_2046"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interview",
            name="questions",
        ),
    ]
