# Generated by Django 3.2.16 on 2022-12-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0002_alter_questionstatistic_mark"),
    ]

    operations = [
        migrations.RenameField(
            model_name="interview",
            old_name="pack_id",
            new_name="pack",
        ),
        migrations.RenameField(
            model_name="interview",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="questionstatistic",
            old_name="question_id",
            new_name="question",
        ),
        migrations.RenameField(
            model_name="questionstatistic",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="questionstatistic",
            name="mark",
            field=models.IntegerField(null=True),
        ),
    ]
