# Generated by Django 3.2.16 on 2022-12-20 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0004_alter_interviewstatistic_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewstatistic",
            name="completion_percentage",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
