# Generated by Django 3.2.16 on 2022-12-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0006_interview_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interview",
            options={
                "verbose_name": "Собеседование",
                "verbose_name_plural": "Собеседования",
            },
        ),
    ]
