name: linters

on:
  push:
    branches: []
  pull_request:
    branches: []


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7", "3.10" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install isort
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Python flake8 Lint
        uses: py-actions/flake8@v2.2.1
        with:
          update-pip: true
          flake8-version: "5.0."
          plugins: "flake8-quotes pep8-naming"
      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics
      - name: isort
        run: |
          cd jjinterviews
          isort . --check
